export type EquipTyping = {
  "id": string;
  "basicDesc": string;
  "desc": string;
  "EffectType": string;
  "fetterID": string;
  "icon": string;
  "name": string;
  "picture": string;
  "planID": string;
  "synthesis1": string;
  "synthesis2": string;
  "tftEquipId": string;
  "type": string;
}
const EquipDataList = [
    {
      "id": "1701",
      "basicDesc": "+10攻击力",
      "desc": "",
      "EffectType": "",
      "fetterID": "",
      "icon": "1001",
      "name": "暴风大剑",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/1001.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "501",
      "type": "基础装备"
    },
    {
      "id": "1702",
      "basicDesc": "+10%攻击速度",
      "desc": "",
      "EffectType": "",
      "fetterID": "",
      "icon": "1002",
      "name": "反曲之弓",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/1002.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "502",
      "type": "基础装备"
    },
    {
      "id": "1703",
      "basicDesc": "+10%法术强度",
      "desc": "",
      "EffectType": "",
      "fetterID": "",
      "icon": "1003",
      "name": "无用大棒",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/1003.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "503",
      "type": "基础装备"
    },
    {
      "id": "1704",
      "basicDesc": "+15法力值",
      "desc": "",
      "EffectType": "",
      "fetterID": "",
      "icon": "1004",
      "name": "女神之泪",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/1004.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "504",
      "type": "基础装备"
    },
    {
      "id": "1705",
      "basicDesc": "+20护甲",
      "desc": "",
      "EffectType": "",
      "fetterID": "",
      "icon": "1005",
      "name": "锁子甲",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/1005.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "505",
      "type": "基础装备"
    },
    {
      "id": "1706",
      "basicDesc": "+20魔法抗性",
      "desc": "",
      "EffectType": "",
      "fetterID": "",
      "icon": "1006",
      "name": "负极斗篷",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/1006.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "506",
      "type": "基础装备"
    },
    {
      "id": "1707",
      "basicDesc": "+150生命上限",
      "desc": "",
      "EffectType": "",
      "fetterID": "",
      "icon": "1007",
      "name": "巨人腰带",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/1007.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "507",
      "type": "基础装备"
    },
    {
      "id": "1708",
      "basicDesc": "他必须做点什么（特殊装备)",
      "desc": "",
      "EffectType": "",
      "fetterID": "",
      "icon": "1008",
      "name": "金铲铲",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/1008.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "508",
      "type": "基础装备"
    },
    {
      "id": "1709",
      "basicDesc": "+5%暴击率 +10%闪避率",
      "desc": "",
      "EffectType": "",
      "fetterID": "",
      "icon": "1009",
      "name": "拳套",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/1009.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "509",
      "type": "基础装备"
    },
    {
      "id": "2701",
      "basicDesc": "+10攻击力 +75%暴击率 +10%暴击伤害",
      "desc": "提供75%暴击几率(包含基础装备)和10%暴击伤害，100%以上的每点暴击几率会转化为+1%暴击伤害。[唯一- 每位英雄仅可装备一件]",
      "EffectType": "",
      "fetterID": "0",
      "icon": "2001",
      "name": "无尽之刃",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2001.png",
      "planID": "7",
      "synthesis1": "1701",
      "synthesis2": "1709",
      "tftEquipId": "535",
      "type": "成型装备"
    },
    {
      "id": "2703",
      "basicDesc": "+10攻击力 +10%法术强度",
      "desc": "提供25%全能吸血。携带者的伤害会对生命值最低的友军造成等额治疗效果。",
      "EffectType": "",
      "fetterID": "",
      "icon": "2003",
      "name": "海克斯科技枪刃",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2003.png",
      "planID": "7",
      "synthesis1": "1701",
      "synthesis2": "1703",
      "tftEquipId": "523",
      "type": "成型装备"
    },
    {
      "id": "2704",
      "basicDesc": "+10攻击力 +15法力值",
      "desc": "攻击回复8额外法力值。",
      "EffectType": "",
      "fetterID": "",
      "icon": "2004",
      "name": "朔极之矛",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2004.png",
      "planID": "7",
      "synthesis1": "1701",
      "synthesis2": "1704",
      "tftEquipId": "525",
      "type": "成型装备"
    },
    {
      "id": "2705",
      "basicDesc": "+10攻击力 +20护甲",
      "desc": "每场战斗仅触发一次：携带者在60%生命值时，会短暂潜行，变为不可被选取状态并移除负面效果。然后，携带者会获得40%额外攻击速度。[唯一- 每位英雄仅可装备一件]",
      "EffectType": "",
      "fetterID": "",
      "icon": "2005",
      "name": "夜之锋刃",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2005.png",
      "planID": "7",
      "synthesis1": "1701",
      "synthesis2": "1705",
      "tftEquipId": "6022",
      "type": "成型装备"
    },
    {
      "id": "2706",
      "basicDesc": "+10攻击力 +20魔法抗性",
      "desc": "提供25%全能吸血每场战斗仅触发1次：在40%生命值时，提供一个护盾，护盾值相当于携带者25%的最大生命值，至多持续5秒。",
      "EffectType": "",
      "fetterID": "",
      "icon": "2006",
      "name": "汲取剑",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2006.png",
      "planID": "7",
      "synthesis1": "1701",
      "synthesis2": "1706",
      "tftEquipId": "529",
      "type": "成型装备"
    },
    {
      "id": "2707",
      "basicDesc": "+10攻击力 +150生命上限",
      "desc": "战斗环节开始时：提供30%攻击速度给携带者和同一排1格内的友军们。[光环类装备]",
      "EffectType": "",
      "fetterID": "",
      "icon": "2007",
      "name": "基克的先驱",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2007.png",
      "planID": "7",
      "synthesis1": "1701",
      "synthesis2": "1707",
      "tftEquipId": "531",
      "type": "成型装备"
    },
    {
      "id": "2709",
      "basicDesc": "+50%攻击速度",
      "desc": "提供50%额外攻击速度（包含基础装备）和1攻击距离。攻击不再会未命中。",
      "EffectType": "",
      "fetterID": "",
      "icon": "2009",
      "name": "疾射火炮",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2009.png",
      "planID": "7",
      "synthesis1": "1702",
      "synthesis2": "1702",
      "tftEquipId": "537",
      "type": "成型装备"
    },
    {
      "id": "2710",
      "basicDesc": "+10%攻击速度 +10%法术强度",
      "desc": "每次攻击提供6%额外攻击速度。这个效果可叠加！",
      "EffectType": "",
      "fetterID": "",
      "icon": "2010",
      "name": "鬼索的狂暴之刃",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2010.png",
      "planID": "7",
      "synthesis1": "1702",
      "synthesis2": "1703",
      "tftEquipId": "539",
      "type": "成型装备"
    },
    {
      "id": "2711",
      "basicDesc": "+20%攻击速度 +15法力值",
      "desc": "提供10%攻击速度（包含基础装备）。携带者的每第3次攻击会释放一道链状闪电，可弹射4名敌人，造成60魔法伤害并使目标的魔法抗性降低50%，持续5秒。[直接伤害类装备]",
      "EffectType": "",
      "fetterID": "",
      "icon": "2011",
      "name": "斯塔缇克电刃",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2011.png",
      "planID": "7",
      "synthesis1": "1702",
      "synthesis2": "1704",
      "tftEquipId": "541",
      "type": "成型装备"
    },
    {
      "id": "2712",
      "basicDesc": "+10%攻击速度 +20护甲",
      "desc": "在携带者攻击或承受伤害时提供2攻击力和2法术强度，至多可叠加25次。这个效果最多叠加25次，且叠满后携带者会获得25护甲和25魔法抗性。",
      "EffectType": "",
      "fetterID": "",
      "icon": "2052",
      "name": "泰坦的坚决",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2052.png",
      "planID": "7",
      "synthesis1": "1702",
      "synthesis2": "1705",
      "tftEquipId": "543",
      "type": "成型装备"
    },
    {
      "id": "2713",
      "basicDesc": "+10%攻击速度 +20魔法抗性 +10攻击力",
      "desc": "携带者获得10攻击力。携带者的攻击会对附近的另一名敌人发射一个弹体，造成携带者70%攻击力的物理伤害。[直接伤害类装备]",
      "EffectType": "",
      "fetterID": "",
      "icon": "2033",
      "name": "卢安娜的飓风",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2033.png",
      "planID": "7",
      "synthesis1": "1702",
      "synthesis2": "1706",
      "tftEquipId": "545",
      "type": "成型装备"
    },
    {
      "id": "2714",
      "basicDesc": "+10%攻击速度 +150生命上限",
      "desc": "在战斗环节开始时，携带者会嘲讽4格内的敌人们。当阵亡后，一个【虚空生物】会爬起来嘲讽附近的敌人。从召唤单位上爬起来的【虚空生物】效能为25%。",
      "EffectType": "",
      "fetterID": "",
      "icon": "2214",
      "name": "兹若特传送门",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2214.png",
      "planID": "7",
      "synthesis1": "1702",
      "synthesis2": "1707",
      "tftEquipId": "547",
      "type": "成型装备"
    },
    {
      "id": "2716",
      "basicDesc": "+75%法术强度",
      "desc": "提供75%额外法术强度（包含基础装备）。",
      "EffectType": "",
      "fetterID": "",
      "icon": "2016",
      "name": "班克斯的魔法帽",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2016.png",
      "planID": "7",
      "synthesis1": "1703",
      "synthesis2": "1703",
      "tftEquipId": "553",
      "type": "成型装备"
    },
    {
      "id": "2717",
      "basicDesc": "+30%法术强度 +15法力值",
      "desc": "提供30额外法术强度。战斗环节开始时：携带者每5秒获得20法术强度。",
      "EffectType": "",
      "fetterID": "",
      "icon": "2017",
      "name": "大天使之杖",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2017.png",
      "planID": "7",
      "synthesis1": "1703",
      "synthesis2": "1704",
      "tftEquipId": "555",
      "type": "成型装备"
    },
    {
      "id": "2718",
      "basicDesc": "+10%法术强度 +20护甲",
      "desc": "战斗环节开始时：为携带者和同一排2格内的友军们提供300/350/400★护盾值，护盾持续15秒。[光环类装备]",
      "EffectType": "",
      "fetterID": "",
      "icon": "2018",
      "name": "钢铁烈阳之匣",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2018.png",
      "planID": "7",
      "synthesis1": "1703",
      "synthesis2": "1705",
      "tftEquipId": "557",
      "type": "成型装备"
    },
    {
      "id": "2719",
      "basicDesc": "+10%法术强度 +20魔法抗性",
      "desc": "2格内的敌人们会被削减50%魔法抗性。在他们施放一次技能时，他们会被震击并受到相当于他们200%最大法力值的魔法伤害。[光环类装备][直接伤害类装备]",
      "EffectType": "",
      "fetterID": "",
      "icon": "2019",
      "name": "离子火花",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2019.png",
      "planID": "7",
      "synthesis1": "1703",
      "synthesis2": "1706",
      "tftEquipId": "559",
      "type": "成型装备"
    },
    {
      "id": "2720",
      "basicDesc": "+40法术强度 +150生命上限",
      "desc": "提供40额外法术强度（包含基础装备）。在携带者用技能造成魔法伤害或真实伤害时，会灼烧目标，在10秒里持续造成真实伤害，总额相当于目标10%的最大生命值，并在灼烧期间降低50%治疗效果。[唯一- 每位英雄仅可装备一件]",
      "EffectType": "",
      "fetterID": "0",
      "icon": "2020",
      "name": "莫雷洛秘典",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2020.png",
      "planID": "7",
      "synthesis1": "1703",
      "synthesis2": "1707",
      "tftEquipId": "561",
      "type": "成型装备"
    },
    {
      "id": "2722",
      "basicDesc": "+50法力值",
      "desc": "提供50初始法力值（包含基础装备）。携带者在施放一个技能后会回复20法力值。[唯一- 每位英雄仅可装备一件]",
      "EffectType": "",
      "fetterID": "",
      "icon": "2222",
      "name": "蓝霸符",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2222.png",
      "planID": "7",
      "synthesis1": "1704",
      "synthesis2": "1704",
      "tftEquipId": "567",
      "type": "成型装备"
    },
    {
      "id": "2723",
      "basicDesc": "+15法力值 +20护甲",
      "desc": "减缓2格内的敌人们30%攻击速度。[光环类装备][唯一- 每位英雄仅可装备一件]",
      "EffectType": "",
      "fetterID": "",
      "icon": "2023",
      "name": "冰霜之心",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2023.png",
      "planID": "7",
      "synthesis1": "1704",
      "synthesis2": "1705",
      "tftEquipId": "569",
      "type": "成型装备"
    },
    {
      "id": "2724",
      "basicDesc": "+15法力值 +20魔法抗性",
      "desc": "战斗环节开始时：提供30法术强度给携带者和同一排1格内的友军们。[光环类装备]",
      "EffectType": "",
      "fetterID": "",
      "icon": "2124",
      "name": "能量圣杯",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2124.png",
      "planID": "7",
      "synthesis1": "1704",
      "synthesis2": "1706",
      "tftEquipId": "571",
      "type": "成型装备"
    },
    {
      "id": "2725",
      "basicDesc": "+15法力值 +150生命上限",
      "desc": "每过5秒治疗1格内的友军们12%的已损失生命值。此外，这些友军们所受的群体目标伤害还会降低25%，持续5秒（伤害减免不会叠加）。[光环类装备]",
      "EffectType": "",
      "fetterID": "",
      "icon": "2025",
      "name": "救赎",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2025.png",
      "planID": "7",
      "synthesis1": "1704",
      "synthesis2": "1707",
      "tftEquipId": "573",
      "type": "成型装备"
    },
    {
      "id": "2727",
      "basicDesc": "+80护甲",
      "desc": "提供80额外护甲（包含基础装备）。使所受暴击的75%额外伤害变得无效。在被一次攻击命中时，对附近的所有敌人造成75/100/150★魔法伤害(每2.5秒一次)。[直接伤害类装备]",
      "EffectType": "",
      "fetterID": "0",
      "icon": "2054",
      "name": "棘刺背心",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2054.png",
      "planID": "7",
      "synthesis1": "1705",
      "synthesis2": "1705",
      "tftEquipId": "579",
      "type": "成型装备"
    },
    {
      "id": "2728",
      "basicDesc": "+20护甲 +20魔法抗性",
      "desc": "每有一个敌人正在以携带者为目标，携带者就会获得16护甲和16魔法抗性。",
      "EffectType": "",
      "fetterID": "0",
      "icon": "2248",
      "name": "石像鬼石板甲",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2248.png",
      "planID": "7",
      "synthesis1": "1705",
      "synthesis2": "1706",
      "tftEquipId": "581",
      "type": "成型装备"
    },
    {
      "id": "2729",
      "basicDesc": "+20护甲 +300生命上限",
      "desc": "提供400额外生命值（包含基础装备）。每过2秒，灼烧2格内的一名随机的敌人，在10秒里持续造成真实伤害，总额相当于其10%最大生命值，并且该敌人受到的所有治疗效果都会降低50%。[唯一- 每位英雄仅可装备一件]",
      "EffectType": "",
      "fetterID": "0",
      "icon": "2329",
      "name": "日炎斗篷",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2329.png",
      "planID": "7",
      "synthesis1": "1705",
      "synthesis2": "1707",
      "tftEquipId": "583",
      "type": "成型装备"
    },
    {
      "id": "2731",
      "basicDesc": "+120魔法抗性",
      "desc": "提供120额外魔法抗性（包含基础装备）。每2秒，每有一个敌人正在以携带者为目标，携带者就会回复1.2%最大生命值。  <color=#F8F8FF><i>如果携带者是一名【龙神】，则所有加成和效果提升20%。</i>",
      "EffectType": "",
      "fetterID": "",
      "icon": "2031",
      "name": "巨龙之爪",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2031.png",
      "planID": "7",
      "synthesis1": "1706",
      "synthesis2": "1706",
      "tftEquipId": "589",
      "type": "成型装备"
    },
    {
      "id": "2732",
      "basicDesc": "+20魔法抗性 +150生命上限",
      "desc": "战斗环节开始时：携带者在对面棋盘召唤一道飓风，来将距离飓风最近的敌人移出战斗5秒。[无视控制免疫效果。][唯一- 每位英雄仅可装备一件]",
      "EffectType": "",
      "fetterID": "",
      "icon": "2032",
      "name": "灵风",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2032.png",
      "planID": "7",
      "synthesis1": "1706",
      "synthesis2": "1707",
      "tftEquipId": "591",
      "type": "成型装备"
    },
    {
      "id": "2734",
      "basicDesc": "+1000生命上限",
      "desc": "提供1000额外生命值（包含基础装备）。",
      "EffectType": "",
      "fetterID": "",
      "icon": "2034",
      "name": "狂徒铠甲",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2034.png",
      "planID": "7",
      "synthesis1": "1707",
      "synthesis2": "1707",
      "tftEquipId": "597",
      "type": "成型装备"
    },
    {
      "id": "2736",
      "basicDesc": "",
      "desc": "你的队伍获得+1最大队伍规模。",
      "EffectType": "1",
      "fetterID": "",
      "icon": "2036",
      "name": "金铲铲冠冕",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2036.png",
      "planID": "7",
      "synthesis1": "1708",
      "synthesis2": "1708",
      "tftEquipId": "603",
      "type": "成型装备"
    },
    {
      "id": "2737",
      "basicDesc": "+15%暴击率 +10%攻击速度",
      "desc": "携带者造成物理伤害时会使目标的护甲被削减50%，持续5秒。这个效果不会叠加。[唯一- 每位英雄仅可装备一件]",
      "EffectType": "",
      "fetterID": "",
      "icon": "2053",
      "name": "最后的轻语",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2053.png",
      "planID": "7",
      "synthesis1": "1702",
      "synthesis2": "1709",
      "tftEquipId": "551",
      "type": "成型装备"
    },
    {
      "id": "2738",
      "basicDesc": "+15%暴击率 +40%法术强度 +10%暴击伤害",
      "desc": "提供10%额外暴击伤害和40额外法术强度。（包含基础装备）。来自携带者的技能的魔法伤害和真实伤害可以造成暴击。",
      "EffectType": "",
      "fetterID": "0",
      "icon": "2038",
      "name": "珠光护手",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2038.png",
      "planID": "7",
      "synthesis1": "1703",
      "synthesis2": "1709",
      "tftEquipId": "565",
      "type": "成型装备"
    },
    {
      "id": "2739",
      "basicDesc": "+15%暴击率 +15法力值",
      "desc": "提供2个效果：—　+15攻击力和+15法术强度。—　15%全能吸血。每一回合，随机使其中一个效果翻倍。",
      "EffectType": "5",
      "fetterID": "",
      "icon": "2039",
      "name": "正义之手",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2039.png",
      "planID": "7",
      "synthesis1": "1704",
      "synthesis2": "1709",
      "tftEquipId": "577",
      "type": "成型装备"
    },
    {
      "id": "2740",
      "basicDesc": "+15%闪避率 +20护甲",
      "desc": "战斗环节开始时：携带者射出一道光束，来使受影响敌人们的最大法力值提升35%，持续到他们施放技能为止。[唯一- 每位英雄仅可装备一件]",
      "EffectType": "",
      "fetterID": "",
      "icon": "2240",
      "name": "静止法衣",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2240.png",
      "planID": "7",
      "synthesis1": "1705",
      "synthesis2": "1709",
      "tftEquipId": "587",
      "type": "成型装备"
    },
    {
      "id": "2741",
      "basicDesc": "+20魔法抗性 +15%闪避率 +20%攻击速度",
      "desc": "提供20%额外攻击速度。战斗环节开始时：提供持续15秒的控制免疫效果。[唯一- 每位英雄仅可装备一件]",
      "EffectType": "",
      "fetterID": "",
      "icon": "2041",
      "name": "水银",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2041.png",
      "planID": "7",
      "synthesis1": "1706",
      "synthesis2": "1709",
      "tftEquipId": "595",
      "type": "成型装备"
    },
    {
      "id": "2742",
      "basicDesc": "+150生命上限 +15%闪避率",
      "desc": "战斗环节开始时：提供一个护盾给携带者和同一排1格内的友军们，护盾会格挡第一个敌方技能的伤害和效果，至多格挡600伤害。[光环类装备]",
      "EffectType": "",
      "fetterID": "",
      "icon": "2042",
      "name": "女妖之爪",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2042.png",
      "planID": "7",
      "synthesis1": "1707",
      "synthesis2": "1709",
      "tftEquipId": "601",
      "type": "成型装备"
    },
    {
      "id": "2744",
      "basicDesc": "+15%暴击率 +15%闪避率",
      "desc": "每一回合：装备2件随机装备。[需要用掉3个装备格][唯一- 每位英雄仅可装备一件]",
      "EffectType": "6",
      "fetterID": "",
      "icon": "2044",
      "name": "秘法手套",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2044.png",
      "planID": "7",
      "synthesis1": "1709",
      "synthesis2": "1709",
      "tftEquipId": "607",
      "type": "成型装备"
    },
    {
      "id": "2745",
      "basicDesc": "携带者获得35/50/65★额外攻击力（包含基础装备）。",
      "desc": "携带者获得35/50/65★额外攻击力（包含基础装备）。",
      "EffectType": "",
      "fetterID": "0",
      "icon": "2045",
      "name": "锐利之刃",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2045.png",
      "planID": "7",
      "synthesis1": "1701",
      "synthesis2": "1701",
      "tftEquipId": "519",
      "type": "成型装备"
    },
    {
      "id": "2746",
      "basicDesc": "+10攻击力 +10%攻击速度",
      "desc": "携带者的攻击和技能造成20%额外伤害，如果目标的最大生命值超过了2200，那么额外伤害会提升至45%。",
      "EffectType": "",
      "fetterID": "0",
      "icon": "2046",
      "name": "巨人捕手",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2046.png",
      "planID": "7",
      "synthesis1": "1701",
      "synthesis2": "1702",
      "tftEquipId": "521",
      "type": "成型装备"
    },
    {
      "id": "2748",
      "basicDesc": "+200生命上限 +20攻击力",
      "desc": "携带者的攻击和技能会击碎敌人60%护甲和魔法抗性，持续5秒。[唯一- 每位英雄仅可装备一件]",
      "EffectType": "",
      "fetterID": "0",
      "icon": "3601",
      "name": "黑曜石切割者",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/3601.png",
      "planID": "7",
      "synthesis1": "",
      "synthesis2": "",
      "tftEquipId": "417",
      "type": "特殊装备"
    },
    {
      "id": "2749",
      "basicDesc": "+25护甲 +25魔法抗性 +200生命上限",
      "desc": "在战斗环节开始时：提供50护甲和50魔法抗性给所有邻格友军，不包括携带者。",
      "EffectType": "",
      "fetterID": "0",
      "icon": "3602",
      "name": "兰顿之圣所",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/3602.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "418",
      "type": "特殊装备"
    },
    {
      "id": "2750",
      "basicDesc": "+20攻击力 +20%暴击率",
      "desc": "携带者的攻击和技能会处决生命值低于10%最大生命值的目标。处决会有60%几率生成1金币。[唯一- 每位英雄仅可装备一件]",
      "EffectType": "",
      "fetterID": "",
      "icon": "3603",
      "name": "金币收集者",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/3603.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "420",
      "type": "特殊装备"
    },
    {
      "id": "2751",
      "basicDesc": "+15攻击力 +15%攻击速度 +40法力值",
      "desc": "每场战斗仅触发一次：在施放一个技能后，在5秒内持续回复共200法力值。[唯一- 每位英雄仅可装备一件]",
      "EffectType": "",
      "fetterID": "0",
      "icon": "3604",
      "name": "魔蕴",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/3604.png",
      "planID": "7",
      "synthesis1": "",
      "synthesis2": "",
      "tftEquipId": "414",
      "type": "特殊装备"
    },
    {
      "id": "2752",
      "basicDesc": "+30法力值 +25护甲 +350生命上限",
      "desc": "战斗环节开始时：携带者会将相距最远的敌人拉到近战距离，并将其晕眩1.5秒。距离内的友军将优先攻击该敌人。[唯一- 每位英雄仅可装备一件]",
      "EffectType": "",
      "fetterID": "0",
      "icon": "3605",
      "name": "火箭助推铁拳",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/3605.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "419",
      "type": "特殊装备"
    },
    {
      "id": "2753",
      "basicDesc": "+150生命上限 +25魔法抗性",
      "desc": "每秒回复自身5%的最大生命值。",
      "EffectType": "",
      "fetterID": "0",
      "icon": "3606",
      "name": "生命盔甲",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/3606.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "412",
      "type": "特殊装备"
    },
    {
      "id": "2754",
      "basicDesc": " +30攻击力 +30%攻击速度 +30%法术强度 +30护甲 +30魔法抗性 +30生命上限",
      "desc": " +30攻击力 +30%攻击速度 +30%法术强度 +30护甲 +30魔法抗性 +30生命上限",
      "EffectType": "",
      "fetterID": "0",
      "icon": "3607",
      "name": "无尽之力",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/3607.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "415",
      "type": "特殊装备"
    },
    {
      "id": "2755",
      "basicDesc": "+200生命上限 +25护甲",
      "desc": "对携带者造成伤害的敌人们会被减缓20%攻击速度，持续2秒。被以这种方式减缓7次后，攻击者会转而被【冻结】相同的时长。每个敌人在10秒里只会被【冻结】一次。[唯一- 每位英雄仅可装备一件]",
      "EffectType": "",
      "fetterID": "0",
      "icon": "3608",
      "name": "永恒凛冬",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/3608.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "416",
      "type": "特殊装备"
    },
    {
      "id": "2756",
      "basicDesc": "+10攻击力 +20%攻击速度 +20护甲",
      "desc": "提供25%全能吸血。携带者受到的50%伤害会转而在4秒里作为非致命伤害来持续扣除。[唯一- 每位英雄仅可装备一件]",
      "EffectType": "",
      "fetterID": "",
      "icon": "3609",
      "name": "死亡之蔑",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/3609.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "413",
      "type": "特殊装备"
    },
    {
      "id": "2757",
      "basicDesc": "+50%法术强度 +50护甲 +50魔法抗性",
      "desc": "每场战斗仅触发一次：当携带者降至40%生命值时，进入持续3秒的免疫伤害状态。[唯一- 每位英雄仅可装备一件]",
      "EffectType": "",
      "fetterID": "",
      "icon": "3610",
      "name": "中娅悖论",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/3610.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "421",
      "type": "特殊装备"
    },
    {
      "id": "2759",
      "basicDesc": "+10攻击力 +75%暴击率",
      "desc": "提供75%暴击几率（包含基础装备）和50%暴击伤害。100%以上的每点暴击几率会转化为1%暴击伤害。[唯一- 每位英雄仅可装备一件]",
      "EffectType": "",
      "fetterID": "",
      "icon": "2548",
      "name": "天顶锋刃",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2548.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5008",
      "type": "特殊装备"
    },
    {
      "id": "2760",
      "basicDesc": "+10攻击力 +30%法术强度",
      "desc": "提供35%全能吸血：造成的伤害会对生命值最低的友军造成等额治疗效果。光明加成：+30法术强度",
      "EffectType": "",
      "fetterID": "",
      "icon": "2549",
      "name": "海克斯科技生命之刃",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2549.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5003",
      "type": "特殊装备"
    },
    {
      "id": "2761",
      "basicDesc": "+10攻击力 +15法力值 +20%法术强度",
      "desc": "攻击回复12额外法力值。光明加成：20法术强度。",
      "EffectType": "",
      "fetterID": "",
      "icon": "2550",
      "name": "希拉娜之矛",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2550.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5004",
      "type": "特殊装备"
    },
    {
      "id": "2762",
      "basicDesc": "+10攻击力 +20护甲",
      "desc": "每场战斗仅触发一次：携带者在60%生命值时和30%生命值时，会短暂潜行，变为不可被选取状态并移除负面效果。然后，携带者会获得40%额外攻击速度。这个效果可以叠加。[唯一- 每位英雄仅可装备一件]",
      "EffectType": "",
      "fetterID": "",
      "icon": "2551",
      "name": "黎明锋刃",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2551.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5005",
      "type": "特殊装备"
    },
    {
      "id": "2763",
      "basicDesc": "+30攻击力 +20魔法抗性",
      "desc": "提供35％全能吸血。每场战斗仅触发1次：在40%生命值时，提供一个护盾，护盾值相当于携带者35％的最大生命值，至多持续5秒。光明加成：+20攻击力。",
      "EffectType": "",
      "fetterID": "",
      "icon": "2552",
      "name": "福佑汲取剑",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2552.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5006",
      "type": "特殊装备"
    },
    {
      "id": "2764",
      "basicDesc": "+10攻击力 +150生命上限",
      "desc": "战斗环节开始时：提供50%攻击速度和10%全能吸血给携带者和同一排1格内的友军们。[光环类装备]",
      "EffectType": "",
      "fetterID": "",
      "icon": "2553",
      "name": "基克的调和",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2553.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5007",
      "type": "特殊装备"
    },
    {
      "id": "2765",
      "basicDesc": "+75%攻击速度",
      "desc": "提供75%额外攻击速度和2攻击距离。攻击不会再未命中。",
      "EffectType": "",
      "fetterID": "",
      "icon": "2554",
      "name": "疾射光明火炮",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2554.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5009",
      "type": "特殊装备"
    },
    {
      "id": "2766",
      "basicDesc": "+25%攻击速度 +10%法术强度",
      "desc": "每次攻击提供+10%额外攻击速度。可无限叠加，持续到战斗环节结束为止。 光明加成：15%攻击速度。",
      "EffectType": "",
      "fetterID": "",
      "icon": "2555",
      "name": "鬼索的清算",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2555.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5010",
      "type": "特殊装备"
    },
    {
      "id": "2767",
      "basicDesc": "+20%攻击速度 +15法力值",
      "desc": "提供10%攻击速度。携带者的每第3次攻击会释放一道链状闪电，可弹射8名敌人，造成110魔法伤害并使目标的魔法抗性降低50%，持续5秒。[直接伤害类装备]",
      "EffectType": "",
      "fetterID": "",
      "icon": "2556",
      "name": "斯塔缇克狂热",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2556.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5011",
      "type": "特殊装备"
    },
    {
      "id": "2768",
      "basicDesc": "+10%攻击速度 +20护甲",
      "desc": "在携带者攻击或承受伤害时提供3攻击力和3法术强度。至多可叠加25次。在叠满层数后，提供50护甲和50魔法抗性。",
      "EffectType": "",
      "fetterID": "",
      "icon": "2557",
      "name": "泰坦的誓言",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2557.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5012",
      "type": "特殊装备"
    },
    {
      "id": "2769",
      "basicDesc": "+40%攻击速度 +20魔法抗性 +10攻击力",
      "desc": "提供10攻击力。携带者的攻击会对附近的另一名敌人发射一个弹体，造成携带者110%攻击力的物理伤害。 光明加成：30%攻击速度。[直接伤害类装备]",
      "EffectType": "",
      "fetterID": "",
      "icon": "2558",
      "name": "卢安娜的风暴",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2558.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5013",
      "type": "特殊装备"
    },
    {
      "id": "2770",
      "basicDesc": "+10%攻击速度 +150生命上限",
      "desc": "在战斗环节开始时:一个带有额外生命值的攻击力的光明版【虚空之母】爬起来并嘲讽附近4格内的敌人。从召唤单位上爬起来的光明版【虚空之母】效能为25%。",
      "EffectType": "",
      "fetterID": "",
      "icon": "2559",
      "name": "兹若特的干涉",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2559.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5014",
      "type": "特殊装备"
    },
    {
      "id": "2771",
      "basicDesc": "+120%法术强度",
      "desc": "提供120额外法术强度。",
      "EffectType": "",
      "fetterID": "",
      "icon": "2560",
      "name": "班克斯的飞升之帽",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2560.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5016",
      "type": "特殊装备"
    },
    {
      "id": "2772",
      "basicDesc": "+30%法术强度 +15法力值",
      "desc": "提供30额外法术强度。战斗环节开始时：携带者每4秒获得25法术强度。",
      "EffectType": "",
      "fetterID": "",
      "icon": "2561",
      "name": "阿福天使之杖",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2561.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5017",
      "type": "特殊装备"
    },
    {
      "id": "2773",
      "basicDesc": "+10%法术强度 +20护甲",
      "desc": "在战斗环节开始时：为携带者和同一排3格内的友军们提供400/500/600★护盾值，护盾持续60秒。光明加成：+200生命值给所有友军[光环类装备]",
      "EffectType": "",
      "fetterID": "",
      "icon": "2562",
      "name": "巨神主峰之匣",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2562.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5018",
      "type": "特殊装备"
    },
    {
      "id": "2774",
      "basicDesc": "+10%法术强度 +20魔法抗性",
      "desc": "3格内的敌人们的魔法抗性被削减50%。在他们施放技能时，他们会被震击并受到相当于他们250%最大法力值的魔法伤害。光明加成：每秒回复1%最大生命值。[光环类装备][直接伤害类装备]",
      "EffectType": "",
      "fetterID": "",
      "icon": "2563",
      "name": "神圣离子火花",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2563.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5019",
      "type": "特殊装备"
    },
    {
      "id": "2775",
      "basicDesc": "+80法术强度 +150生命上限",
      "desc": "提供80额外法术强度（包含基础装备）。在携带者用技能造成魔法伤害或真实伤害时，会灼烧目标，在30秒里持续造成真实伤害，总额相当于目标60%的最大生命值，并在灼烧期间降低50%治疗效果。[唯一- 每位英雄仅可装备一件]",
      "EffectType": "",
      "fetterID": "0",
      "icon": "2564",
      "name": "莫雷洛圣典",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2564.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5020",
      "type": "特殊装备"
    },
    {
      "id": "2776",
      "basicDesc": "+50法力值 +30%法术强度",
      "desc": "提供50初始法力值（包含基础装备）。在携带者施放一个技能后会回复30法力值。光明加成：+30法术强度.[唯一- 每位英雄仅可装备一件]",
      "EffectType": "",
      "fetterID": "",
      "icon": "2565",
      "name": "圣蓝祝福",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2565.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5022",
      "type": "特殊装备"
    },
    {
      "id": "2777",
      "basicDesc": "+45法力值 +20护甲",
      "desc": "减缓2格内的敌人们50%攻击速度。光明加成： +30初始法力值。[唯一- 每位英雄仅可装备一件]",
      "EffectType": "",
      "fetterID": "",
      "icon": "2566",
      "name": "圣金冰霜之心",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2566.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5023",
      "type": "特殊装备"
    },
    {
      "id": "2778",
      "basicDesc": "+15法力值 +20魔法抗性",
      "desc": "战斗环节开始时:提供50法术强度和10%全能吸血给携带者和同一排1格内的友军们。[光环类装备]",
      "EffectType": "",
      "fetterID": "",
      "icon": "2567",
      "name": "济世圣杯",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2567.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5024",
      "type": "特殊装备"
    },
    {
      "id": "2779",
      "basicDesc": "+15法力值 +300生命上限",
      "desc": "每过5秒治疗2格内的友军们18%的已损失生命值。此外，这些友军们所受的群体目标伤害还会降低25%，持续5秒（伤害减免不会叠加）。光明加成：+150生命值。[光环类装备]",
      "EffectType": "",
      "fetterID": "",
      "icon": "2568",
      "name": "赦除",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2568.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5025",
      "type": "特殊装备"
    },
    {
      "id": "2780",
      "basicDesc": "+100护甲",
      "desc": "提供100额外护甲。使所受暴击的所有额外伤害变得无效。在被一次攻击命中时，对附近的所有敌人造成125/175/225★魔法伤害(每2.5秒一次)。[直接伤害类装备]",
      "EffectType": "",
      "fetterID": "",
      "icon": "2569",
      "name": "瑰刺背心",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2569.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5027",
      "type": "特殊装备"
    },
    {
      "id": "2781",
      "basicDesc": "+20护甲 +20魔法抗性",
      "desc": "每有一个敌人正在以携带者为目标，携带者就会获得18护甲和18魔法抗性。光明加成：每秒回复1％最大生命值。",
      "EffectType": "",
      "fetterID": "",
      "icon": "2570",
      "name": "天神石板甲",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2570.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5028",
      "type": "特殊装备"
    },
    {
      "id": "2782",
      "basicDesc": "+20护甲 +600生命上限",
      "desc": "携带者获得额外生命值，每过1.5秒，灼烧4格内的一名随机的敌人，在30秒里持续造成真实伤害，总额相当于其60%最大生命值，并且该敌人受到的所有治疗效果都会降低50%。[唯一- 每位英雄仅可装备一件]",
      "EffectType": "",
      "fetterID": "0",
      "icon": "2571",
      "name": "日光斗篷",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2571.png",
      "planID": "7",
      "synthesis1": "",
      "synthesis2": "",
      "tftEquipId": "5029",
      "type": "特殊装备"
    },
    {
      "id": "2783",
      "basicDesc": "+180魔法抗性",
      "desc": "提供180额外魔法抗性。每1.5秒，每有一个敌人正在以携带者为目标，携带者就会回复2.5%最大生命值。\n如果携带者是一名龙神，则所有加成和效果提升20%。",
      "EffectType": "",
      "fetterID": "0",
      "icon": "2572",
      "name": "巨龙意志",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2572.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5031",
      "type": "特殊装备"
    },
    {
      "id": "2784",
      "basicDesc": "+20魔法抗性 +150生命上限",
      "desc": "战斗环节开始时：携带者在对面棋盘召唤一道飓风，来将距离飓风最近的敌人移出战斗8秒。光明加成：10%攻击速度给所有友军。[无视控制免疫效果。][唯一- 每位英雄仅可装备一件]",
      "EffectType": "",
      "fetterID": "",
      "icon": "2573",
      "name": "寒风",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2573.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5032",
      "type": "特殊装备"
    },
    {
      "id": "2785",
      "basicDesc": "+1600生命上限",
      "desc": "提供1600额外生命值。光明加成：携带者每秒回复1%最大生命值。",
      "EffectType": "",
      "fetterID": "",
      "icon": "2574",
      "name": "狂徒之傲",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2574.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5034",
      "type": "特殊装备"
    },
    {
      "id": "2786",
      "basicDesc": "+50%暴击率 +10%攻击速度",
      "desc": "携带者造成物理伤害时会使目标的护甲会被减少50％，持续至战斗环节结束为止。这个效果不会叠加。光明加成：35％暴击几率。[唯一- 每位英雄仅可装备一件]",
      "EffectType": "",
      "fetterID": "",
      "icon": "2575",
      "name": "永恒轻语",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2575.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5015",
      "type": "特殊装备"
    },
    {
      "id": "2787",
      "basicDesc": "+15%暴击率 +60%法术强度",
      "desc": "提供40%额外暴击伤害和60额外法术强度。",
      "EffectType": "",
      "fetterID": "0",
      "icon": "2576",
      "name": "圣洁珠光护手",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2576.png",
      "planID": "7",
      "synthesis1": "",
      "synthesis2": "",
      "tftEquipId": "5021",
      "type": "特殊装备"
    },
    {
      "id": "2788",
      "basicDesc": "+15%暴击率 +15法力值",
      "desc": "提供2个效果：— 40攻击力和40法术强度。— 40％全能吸血。 来自携带者的技能的魔法伤害和真实伤害可以造成暴击。",
      "EffectType": "5",
      "fetterID": "",
      "icon": "2577",
      "name": "绝对正义之拳",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2577.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5026",
      "type": "特殊装备"
    },
    {
      "id": "2789",
      "basicDesc": "+15闪避率 +20护甲",
      "desc": "在战斗环节开始时：携带者射出一道更宽的光束，来使受影响敌人们的最大法力值提升50%，持续到他们施放技能为止。光明加成：15初始法力值给所有友军。[唯一- 每位英雄仅可装备一件]",
      "EffectType": "",
      "fetterID": "",
      "icon": "2578",
      "name": "崇敬法衣",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2578.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5030",
      "type": "特殊装备"
    },
    {
      "id": "2790",
      "basicDesc": "+20魔法抗性 +15%闪避率 +50%攻击速度",
      "desc": "提供50%额外攻击速度。 战斗环节开始时：提供持续30秒的控制免疫效果。[唯一- 每位英雄仅可装备一件]",
      "EffectType": "",
      "fetterID": "",
      "icon": "2579",
      "name": "至速水银",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2579.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5033",
      "type": "特殊装备"
    },
    {
      "id": "2791",
      "basicDesc": "+150生命上限 +15%闪避率",
      "desc": "在战斗环节开始时：提供一个护盾给你的队伍来格挡第一个敌方技能，至多格挡600伤害。光明加成：+50生命值给所有友军",
      "EffectType": "",
      "fetterID": "",
      "icon": "2580",
      "name": "女妖之沉默",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2580.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5035",
      "type": "特殊装备"
    },
    {
      "id": "2792",
      "basicDesc": "+15%暴击率 +15%闪避率",
      "desc": "每一回合：装备2件随机光明装备。[唯一- 每位英雄仅可装备一件]",
      "EffectType": "15",
      "fetterID": "",
      "icon": "2581",
      "name": "侠盗拳套",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2581.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5036",
      "type": "特殊装备"
    },
    {
      "id": "2793",
      "basicDesc": "提供50/75/100★额外攻击力。",
      "desc": "提供50/75/100★额外攻击力。",
      "EffectType": "",
      "fetterID": "0",
      "icon": "2582",
      "name": "光辉之刃",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2582.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5001",
      "type": "特殊装备"
    },
    {
      "id": "2794",
      "basicDesc": "+10攻击力 +10%攻击速度",
      "desc": "携带者的技能和攻击造成35%额外伤害。如果目标的最大生命值超过了2200，那么额外伤害会提升至70%。",
      "EffectType": "",
      "fetterID": "",
      "icon": "2583",
      "name": "恶魔捕手",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/2583.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "5002",
      "type": "特殊装备"
    },
    {
      "id": "3701",
      "basicDesc": "",
      "desc": "用在一位英雄身上，即可生成一个该英雄的1星版本到你的备战区。[消耗品-这个物品会在使用后消失]",
      "EffectType": "8",
      "fetterID": "",
      "icon": "3701",
      "name": "英雄复制器",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/3701.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "0",
      "type": "特殊装备"
    },
    {
      "id": "3702",
      "basicDesc": "",
      "desc": "用在一位英雄身上即可解除其所有装备，并将这些装备都随机转换为新装备。［相同品质：重铸将提供一件拥有相同类型和品质的新装备。］［无法对战斗中的英雄使用，或对【金铲铲冠冕】使用。］[消耗品-这个物品会在使用后消失。]",
      "EffectType": "19",
      "fetterID": "",
      "icon": "3502",
      "name": "重铸器",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/3502.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "0",
      "type": "特殊装备"
    },
    {
      "id": "3703",
      "basicDesc": "",
      "desc": "用在一位英雄身上即可取下其所有装备。[无法对战斗中的英雄使用。][消耗品-这个物品会在使用后消失。]",
      "EffectType": "20",
      "fetterID": "",
      "icon": "3503",
      "name": "装备拆卸器",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/3503.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "0",
      "type": "特殊装备"
    },
    {
      "id": "3704",
      "basicDesc": "",
      "desc": "对一个英雄使用这个，即可使商店进行一次特殊刷新且该次刷新仅包含与该英雄拥有一个相同羁绊的英雄。[消耗品 - 这个物品会在使用后消失。]",
      "EffectType": "22",
      "fetterID": "",
      "icon": "3504",
      "name": "灌铅骰子",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/3504.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "0",
      "type": "特殊装备"
    },
    {
      "id": "3705",
      "basicDesc": "",
      "desc": "将这本书拖拽到商店处售卖可开启一个全是纹章的武器库！",
      "EffectType": "23",
      "fetterID": "",
      "icon": "3505",
      "name": "纹章之书",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/3505.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "0",
      "type": "特殊装备"
    },
    {
      "id": "3710",
      "basicDesc": "",
      "desc": "诺姆希需要吃掉这么多小点心才能升级！",
      "EffectType": "13",
      "fetterID": "",
      "icon": "3710",
      "name": "美味点心",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/3710.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "7033",
      "type": "特殊装备"
    },
    {
      "id": "4702",
      "basicDesc": "+150生命上限",
      "desc": "携带者获得【神龙烈焰】羁绊[唯一- 每位英雄仅可装备一件]",
      "EffectType": "2",
      "fetterID": "141",
      "icon": "4702",
      "name": "神龙烈焰纹章",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/4702.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "7016",
      "type": "特殊装备"
    },
    {
      "id": "4704",
      "basicDesc": "+10攻击力",
      "desc": "携带者获得【金鳞龙】羁绊[唯一- 每位英雄仅可装备一件]",
      "EffectType": "2",
      "fetterID": "143",
      "icon": "4704",
      "name": "金鳞龙纹章",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/4704.png",
      "planID": "7",
      "synthesis1": "1708",
      "synthesis2": "1701",
      "tftEquipId": "7001",
      "type": "特殊装备"
    },
    {
      "id": "4705",
      "basicDesc": "+150生命上限",
      "desc": "携带者获得【幽影龙】羁绊[唯一- 每位英雄仅可装备一件]",
      "EffectType": "2",
      "fetterID": "144",
      "icon": "4705",
      "name": "幽影龙纹章",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/4705.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "7011",
      "type": "特殊装备"
    },
    {
      "id": "4706",
      "basicDesc": "+150生命上限",
      "desc": "携带者获得【玉龙】羁绊[唯一- 每位英雄仅可装备一件]",
      "EffectType": "2",
      "fetterID": "145",
      "icon": "4706",
      "name": "玉龙纹章",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/4706.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "7019",
      "type": "特殊装备"
    },
    {
      "id": "4707",
      "basicDesc": "+20魔法抗性",
      "desc": "携带者获得【幻镜龙】羁绊[唯一- 每位英雄仅可装备一件]",
      "EffectType": "2",
      "fetterID": "146",
      "icon": "4707",
      "name": "幻镜龙纹章",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/4707.png",
      "planID": "7",
      "synthesis1": "1708",
      "synthesis2": "1706",
      "tftEquipId": "7006",
      "type": "特殊装备"
    },
    {
      "id": "4708",
      "basicDesc": "+150生命上限",
      "desc": "携带者获得【屠龙勇士】羁绊[唯一- 每位英雄仅可装备一件]",
      "EffectType": "2",
      "fetterID": "147",
      "icon": "4708",
      "name": "屠龙勇士纹章",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/4708.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "7009",
      "type": "特殊装备"
    },
    {
      "id": "4709",
      "basicDesc": "+150生命上限",
      "desc": "携带者获得【冒险家】羁绊[唯一- 每位英雄仅可装备一件]",
      "EffectType": "2",
      "fetterID": "148",
      "icon": "4709",
      "name": "冒险家纹章",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/4709.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "7018",
      "type": "特殊装备"
    },
    {
      "id": "4710",
      "basicDesc": "+150生命上限",
      "desc": "携带者获得【风暴龙】羁绊[唯一- 每位英雄仅可装备一件]",
      "EffectType": "2",
      "fetterID": "149",
      "icon": "4710",
      "name": "风暴龙纹章",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/4710.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "7013",
      "type": "特殊装备"
    },
    {
      "id": "4713",
      "basicDesc": "+10%攻击速度",
      "desc": "携带者获得【怒翼龙】羁绊[唯一- 每位英雄仅可装备一件]",
      "EffectType": "2",
      "fetterID": "152",
      "icon": "4713",
      "name": "怒翼龙纹章",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/4713.png",
      "planID": "7",
      "synthesis1": "1708",
      "synthesis2": "1702",
      "tftEquipId": "7002",
      "type": "特殊装备"
    },
    {
      "id": "4714",
      "basicDesc": "+10%法术强度",
      "desc": "携带者获得【神龙尊者】羁绊[唯一- 每位英雄仅可装备一件]",
      "EffectType": "3",
      "fetterID": "100",
      "icon": "4714",
      "name": "神龙尊者纹章",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/4714.png",
      "planID": "7",
      "synthesis1": "1708",
      "synthesis2": "1703",
      "tftEquipId": "7003",
      "type": "特殊装备"
    },
    {
      "id": "4715",
      "basicDesc": "+15法力值",
      "desc": "携带者获得【法师】羁绊[唯一- 每位英雄仅可装备一件]",
      "EffectType": "3",
      "fetterID": "101",
      "icon": "4715",
      "name": "法师纹章",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/4715.png",
      "planID": "7",
      "synthesis1": "1708",
      "synthesis2": "1704",
      "tftEquipId": "7004",
      "type": "特殊装备"
    },
    {
      "id": "4716",
      "basicDesc": "+150生命上限",
      "desc": "携带者获得【魔导师】羁绊[唯一- 每位英雄仅可装备一件]",
      "EffectType": "3",
      "fetterID": "102",
      "icon": "4716",
      "name": "魔导师纹章",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/4716.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "7017",
      "type": "特殊装备"
    },
    {
      "id": "4717",
      "basicDesc": "+5%闪避率 +10%暴击率",
      "desc": "携带者获得【刺客】羁绊[唯一- 每位英雄仅可装备一件]",
      "EffectType": "3",
      "fetterID": "103",
      "icon": "4717",
      "name": "刺客纹章",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/4717.png",
      "planID": "7",
      "synthesis1": "1708",
      "synthesis2": "1709",
      "tftEquipId": "7008",
      "type": "特殊装备"
    },
    {
      "id": "4718",
      "basicDesc": "+150生命上限",
      "desc": "携带者获得【迅捷射手】羁绊[唯一- 每位英雄仅可装备一件]",
      "EffectType": "3",
      "fetterID": "104",
      "icon": "4718",
      "name": "迅捷射手纹章",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/4718.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "7015",
      "type": "特殊装备"
    },
    {
      "id": "4719",
      "basicDesc": "+150生命上限",
      "desc": "携带者获得【强袭炮手】羁绊[唯一- 每位英雄仅可装备一件]",
      "EffectType": "3",
      "fetterID": "105",
      "icon": "4719",
      "name": "强袭炮手纹章",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/4719.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "7010",
      "type": "特殊装备"
    },
    {
      "id": "4720",
      "basicDesc": "+150生命上限",
      "desc": "携带者获得【格斗家】羁绊[唯一- 每位英雄仅可装备一件]",
      "EffectType": "3",
      "fetterID": "106",
      "icon": "4720",
      "name": "格斗家纹章",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/4720.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "7031",
      "type": "特殊装备"
    },
    {
      "id": "4721",
      "basicDesc": "+150生命上限",
      "desc": "携带者获得【护卫】羁绊[唯一- 每位英雄仅可装备一件]",
      "EffectType": "3",
      "fetterID": "107",
      "icon": "4721",
      "name": "护卫纹章",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/4721.png",
      "planID": "7",
      "synthesis1": "1708",
      "synthesis2": "1707",
      "tftEquipId": "7007",
      "type": "特殊装备"
    },
    {
      "id": "4722",
      "basicDesc": "+150生命上限",
      "desc": "携带者获得【秘术师】羁绊[唯一- 每位英雄仅可装备一件]",
      "EffectType": "3",
      "fetterID": "108",
      "icon": "4722",
      "name": "秘术师纹章",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/4722.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "7014",
      "type": "特殊装备"
    },
    {
      "id": "4725",
      "basicDesc": "+150生命上限",
      "desc": "携带者获得【狂刃战士】羁绊[唯一- 每位英雄仅可装备一件]",
      "EffectType": "3",
      "fetterID": "111",
      "icon": "4725",
      "name": "狂刃战士纹章",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/4725.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "7012",
      "type": "特殊装备"
    },
    {
      "id": "4726",
      "basicDesc": "+20护甲",
      "desc": "携带者获得【重骑兵】羁绊[唯一- 每位英雄仅可装备一件]",
      "EffectType": "3",
      "fetterID": "112",
      "icon": "4726",
      "name": "重骑兵纹章",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/4726.png",
      "planID": "7",
      "synthesis1": "1708",
      "synthesis2": "1705",
      "tftEquipId": "7005",
      "type": "特殊装备"
    },
    {
      "id": "4729",
      "basicDesc": "+150生命上限",
      "desc": "携带者获得【传奇半神】羁绊[唯一- 每位英雄仅可装备一件]",
      "EffectType": "3",
      "fetterID": "115",
      "icon": "4729",
      "name": "传奇半神纹章",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/4729.png",
      "planID": "7",
      "synthesis1": "0",
      "synthesis2": "0",
      "tftEquipId": "7020",
      "type": "特殊装备"
    },
    {
      "id": "5702",
      "basicDesc": "+30%法术强度 +30法力值",
      "desc": "提供1×你的金币存款的法术强度(在80金币时达到最大值)，并在击杀一名敌人后有50%几率掉落2金币。",
      "EffectType": "",
      "fetterID": "0",
      "icon": "5702",
      "name": "御金师之杖",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/5702.png",
      "planID": "7",
      "synthesis1": "",
      "synthesis2": "",
      "tftEquipId": "7025",
      "type": "特殊装备"
    },
    {
      "id": "5703",
      "basicDesc": "+10攻击力 +10%攻击速度",
      "desc": "提供1×你的金币存款的攻击力(在80金币时达到最大值)。每次攻击时，这件装备提供1个层数，至多100层。在满层时，提供8金币和1件基础装备。",
      "EffectType": "28",
      "fetterID": "0",
      "icon": "5703",
      "name": "德莱文之斧",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/5703.png",
      "planID": "7",
      "synthesis1": "",
      "synthesis2": "",
      "tftEquipId": "7023",
      "type": "特殊装备"
    },
    {
      "id": "5704",
      "basicDesc": "+300生命上限",
      "desc": "在承受伤害时提供1护甲、1魔法抗性和5生命值，这个效果至多叠加40次。在满层时，提供2金币。",
      "EffectType": "",
      "fetterID": "0",
      "icon": "5704",
      "name": "大亨之铠",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/5704.png",
      "planID": "7",
      "synthesis1": "",
      "synthesis2": "",
      "tftEquipId": "7022",
      "type": "特殊装备"
    },
    {
      "id": "5705",
      "basicDesc": "+150生命上限",
      "desc": "在携带者阵亡7次之后，这件装备会被摧毁。在被摧毁时，提供装备【钻石之手】、1个【英雄复制器】和15金币。",
      "EffectType": "31",
      "fetterID": "0",
      "icon": "5705",
      "name": "坚定投资器",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/5705.png",
      "planID": "7",
      "synthesis1": "",
      "synthesis2": "",
      "tftEquipId": "7027",
      "type": "特殊装备"
    },
    {
      "id": "5706",
      "basicDesc": "+200生命上限 +20%法术强度",
      "desc": "每场战斗仅触发一次：当携带者降至66%生命值和33%生命值时，获得持续1秒的伤害免疫效果和1金币。",
      "EffectType": "",
      "fetterID": "0",
      "icon": "5706",
      "name": "钻石之手",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/5706.png",
      "planID": "7",
      "synthesis1": "",
      "synthesis2": "",
      "tftEquipId": "7028",
      "type": "特殊装备"
    },
    {
      "id": "5707",
      "basicDesc": "+500生命上限",
      "desc": "每场战斗仅触发一次：如果携带者在战斗环节开始15秒后仍然存活，那么每3个仍存活的友军会提供1金币，并且每个仍存活的友军造成的伤害提升，数额相当于1%×你的金币存款(在80金币时达到最大值)。",
      "EffectType": "",
      "fetterID": "0",
      "icon": "5707",
      "name": "无用大宝石",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/5707.png",
      "planID": "7",
      "synthesis1": "",
      "synthesis2": "",
      "tftEquipId": "7024",
      "type": "特殊装备"
    },
    {
      "id": "5708",
      "basicDesc": "+30%法术强度 +30%攻击速度",
      "desc": "提供1%×你的金币存款的攻击速度(在80金币时达到最大值)。每次攻击有6%几率掉落1金币。",
      "EffectType": "",
      "fetterID": "0",
      "icon": "5708",
      "name": "投机者之刃",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/5708.png",
      "planID": "7",
      "synthesis1": "",
      "synthesis2": "",
      "tftEquipId": "7026",
      "type": "特殊装备"
    },
    {
      "id": "5709",
      "basicDesc": "+100生命上限",
      "desc": "每过4秒，携带者的下一次攻击造成9001×你的金币存款的真实伤害。",
      "EffectType": "",
      "fetterID": "0",
      "icon": "5709",
      "name": "群英冠冕",
      "picture": "https://game.gtimg.cn/images/lol/act/jkzlk/s5/equip/5709.png",
      "planID": "7",
      "synthesis1": "",
      "synthesis2": "",
      "tftEquipId": "7030",
      "type": "特殊装备"
    }
  ];


export default EquipDataList;
